[package]
name = "audio-sort"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
eframe = "0.32.0"
gstreamer = "0.24.0"
gstreamer-app = "0.24.0"
gstreamer-audio = "0.24.0"
itertools = "0.14.0"
rfd = "0.15.4"
